services:
  - type: web
    name: waqeel-backend
    runtime: python
    buildCommand: cd waqeel-backend && pip install -r requirements.txt
    startCommand: cd waqeel-backend && uvicorn main:app --host=0.0.0.0 --port=$PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
